:importjava.awt.event.ActionEvent::SEMICOLON:
:importjava.awt.event.ActionListener::SEMICOLON:
:importjavax.swing.JFrame::SEMICOLON:
:EMPTY:
:public::CLASS::Q2_Viewer::EXTENDS::JFrameimplementsActionListener::LBRACE:
:EMPTY:
:AND::Override:
:publicvoidactionPerformed::LBRACKET::ActionEventarg0::RBRACKET::LBRACE:
:COMMENT:
:EMPTY:
:RBRACE:
:EMPTY:
:RBRACE:
:EOF: